name: Zip Release
on:
  push:
    branches:
      - master
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create release dir
        run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' --exclude='LICENSE' --exclude='README.md' . ./release
      - name: Switch to release dir
        run: |
          cd release
          ls -la
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          REPO_OWNER: RuchirChawdhry
